// This file is auto-generated by the i18n type-generation script. Do not edit manually.
import 'i18next';

import common from './locales/en/common.json';
import confraria from './locales/en/confraria.json';
import encyclopedia from './locales/en/encyclopedia.json';
import home from './locales/en/home.json';
import lesson_ui from './locales/en/lesson_ui.json';
import lessons from './locales/en/lessons.json';
import map from './locales/en/map.json';
import quiz from './locales/en/quiz.json';
import quiz_questions from './locales/en/quiz_questions.json';
import settings from './locales/en/settings.json';

declare module 'i18next' {
  interface CustomTypeOptions {
    defaultNS: 'home';
    resources: {
      common: typeof common;
      confraria: typeof confraria;
      encyclopedia: typeof encyclopedia;
      home: typeof home;
      lesson_ui: typeof lesson_ui;
      lessons: typeof lessons;
      map: typeof map;
      quiz: typeof quiz;
      quiz_questions: typeof quiz_questions;
      settings: typeof settings;
    };
  }
}
